apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-up
  namespace: order-up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-up
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-up
    spec:
      containers:
      - image: localhost:5000/server
        imagePullPolicy: Always
        name: server
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
